version: '3.7'

services:
  nginx:
    container_name: NovaManagerNginx
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api

  api:
    container_name: NovaManagerBackend
    image: marquesluis/novamanager:latest
    volumes:
      - static_volume:/app/staticfiles
    restart: always
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - api_db

  api_db:
    container_name: NovaManagerDatabase
    image: mysql:8
    env_file:
      - ./.env.prod
    volumes:
      - nova_api_data:/var/lib/mysql
    restart: always

  adminer:
    container_name: NovaManagerAdminer
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  nova_api_data:
  static_volume: